### ISSUE TITLE
I would love to use this but i can't

### ISSUE THREAD

**Issue by turismo444** [lequietriot/RuneScape-MIDI-Player-Suite#3]
I downloaded IntelliJ but in line 3044 in GUI there's this bug:
There is no Method such as readAllBytes

is there any other way i can use this?

and btw i love that i finally found something that can play rs music how it supposed to play :)

**Comment by lequietriot** [comment]
Hi, have you tried using the SDK version 12? You can also try checking the releases for a jar file.

**Comment by turismo444** [comment]
Thanks for the quick response!
Installed JDK12, the redAllBytes Bug is away, but still if i try to play a midi file, this comes:
Tried in Eclipse this time, because intellij still makes more problems

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at main.GUI$StartButtonListener.actionPerformed(GUI.java:494)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2762)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by lequietriot** [comment]
Have you tried referencing the Displee-RS-Cache-Library.jar in the project? I built this project in IntelliJ because I had issues trying to implement some stuff I wanted in Eclipse, so it would most likely work better in IntelliJ. If you haven't checked out the Project Structure > Project Settings > Libraries > + then add the .jar file, then that might be causing most issues.

**Comment by turismo444** [comment]
I managed to run it finally without errors, i dont exactly know why :) man, i also forgot to load a soundbank, didnt know that that was required as well..
now i can play everything, but it doenst quite sound like the runescape sound, which i hoped to achieve. its very close, but i just need the same :P isnt there a way to get the original soundfont from runescape?

**Comment by turismo444** [comment]
i plan to rip everything from oldschoolrunescape, which will be a pain in the ass. do you know someone that already did that and i can download the mp3's somewhere? i am searching year after year for it in the internet but noone seem to do it ..

**Comment by lequietriot** [comment]
Yeah as far as I know no one has dumped/ripped every song yet. It's possible to do but can be a very painful manual process sometimes. This tool is especially helpful with the encode MIDI feature and soundbank packing/dumping, you should be able to load the cache with this tool then encode a loaded MIDI into the cache of a private server then run both server & client to hear it. If you want to dump what you hear from the client, you can make the client write the sample buffer to a file instead of the SourceDataLine.

**Comment by lequietriot** [comment]
@turismo444 Finally managed to implement the official in-game sound, check out the ReadMe file to see how you can set it up to do so. Feel free to let me know if you have any additional issues.
