### ISSUE TITLE
A JNI error has occurred

### ISSUE THREAD

**Issue by Toshiba1127** [lequietriot/RuneScape-MIDI-Player-Suite#6]
I got this error when i try to launch it. I have re-installed latest version of Java 8

![image](https://user-images.githubusercontent.com/64008639/97085753-a7350880-161f-11eb-9165-abaa9bc5550a.png)

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: main/Main has been compiled by a more recent version of the Java Runtime (class file version 56.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
```

**Comment by lequietriot** [comment]
@Toshiba1127 Are you trying to launch a released jar file, or are you using IntelliJ IDEA to build and run it?

**Comment by Toshiba1127** [comment]
I'm trying to launch it and also via CMD `java -jar`

**Comment by lequietriot** [comment]
@Toshiba1127 Try building it in IntelliJ IDEA instead, there were some issues with the jar file itself running properly in some cases.

**Comment by Toshiba1127** [comment]
I installed IntelliJ IDEA and it took me very long time to figure it out how to configure and build. It works, but gave up because it was too buggy. I got the mp3 from other sites I needed
